// Auto-generated by BoltFFI. Do not edit.
// swiftlint:disable all
// swiftformat:disable all

import Foundation
import MccopilotBridgeFFI
typealias BoltFFICallbackHandle = MccopilotBridgeFFI.BoltFFICallbackHandle

public struct FfiError: Error {
    public let message: String
    public init(message: String) { self.message = message }
    public init(fromC c: MccopilotBridgeFFI.FfiError) {
        self.message = stringFromFfi(c.message)
    }
}

/// FFI 导出的数据类型
public struct ByteArray: Hashable, Equatable, Sendable {
    public var data: Data

    public init(data: Data) {
        self.data = data
    }

}

extension ByteArray: WireCodable {
    @inlinable static func decode(from reader: inout WireReader) -> ByteArray {
        ByteArray(data: reader.readBytes())
    }
    @inlinable func encode(to writer: inout WireWriter) {
        writer.writeBytes(self.data)
    }
}

public struct StringResult: Hashable, Equatable, Sendable {
    public var success: Bool
    public var data: String
    public var error: String?

    public init(success: Bool, data: String, error: String? = nil) {
        self.success = success
        self.data = data
        self.error = error
    }

}

extension StringResult: WireCodable {
    @inlinable static func decode(from reader: inout WireReader) -> StringResult {
        StringResult(success: reader.readBool(), data: reader.readString(), error: reader.readOptional { reader in reader.readString() })
    }
    @inlinable func encode(to writer: inout WireWriter) {
        writer.writeBool(self.success)
        writer.writeString(self.data)
        writer.writeOptional(self.error) { writer, v in writer.writeString(v) }
    }
}

public struct BytesResult: Hashable, Equatable, Sendable {
    public var success: Bool
    public var data: Data
    public var error: String?

    public init(success: Bool, data: Data, error: String? = nil) {
        self.success = success
        self.data = data
        self.error = error
    }

}

extension BytesResult: WireCodable {
    @inlinable static func decode(from reader: inout WireReader) -> BytesResult {
        BytesResult(success: reader.readBool(), data: reader.readBytes(), error: reader.readOptional { reader in reader.readString() })
    }
    @inlinable func encode(to writer: inout WireWriter) {
        writer.writeBool(self.success)
        writer.writeBytes(self.data)
        writer.writeOptional(self.error) { writer, v in writer.writeString(v) }
    }
}

/// Argon2 参数配置 (用于 BoltFFI)
public struct Argon2Params: Hashable, Equatable, Sendable {
    /// 内存成本（KB），默认 64MB
    public var memoryCost: UInt32
    /// 时间成本（迭代次数），默认 3
    public var timeCost: UInt32
    /// 并行度，默认 4
    public var parallelism: UInt32
    /// 输出长度（字节），默认 32
    public var outputLength: UInt32

    public init(memoryCost: UInt32, timeCost: UInt32, parallelism: UInt32, outputLength: UInt32) {
        self.memoryCost = memoryCost
        self.timeCost = timeCost
        self.parallelism = parallelism
        self.outputLength = outputLength
    }

}

extension Argon2Params: WireCodable {
    @inlinable static func decode(from reader: inout WireReader) -> Argon2Params { reader.readBlittable() }
    @inlinable func encode(to writer: inout WireWriter) { writer.writeBlittable(self) }
}

/// 哈希算法类型 (用于 BoltFFI)
public enum HashAlgorithm: Int32, Hashable, Sendable, CaseIterable {
    case sha256 = 0
    case sha384 = 1
    case sha512 = 2

    @usableFromInline init(fromC c: Int32) { self = HashAlgorithm(rawValue: c)! }
    @usableFromInline var cValue: Int32 { rawValue }

}

extension HashAlgorithm: WireCodable {
    @inlinable static func decode(from reader: inout WireReader) -> HashAlgorithm { HashAlgorithm(rawValue: reader.readI32())! }
    @inlinable func encode(to writer: inout WireWriter) { writer.writeI32(rawValue) }
}

/// AES 密钥长度
public enum AesKeySize: Int32, Hashable, Sendable, CaseIterable {
    case aes128 = 0
    case aes192 = 1
    case aes256 = 2

    @usableFromInline init(fromC c: Int32) { self = AesKeySize(rawValue: c)! }
    @usableFromInline var cValue: Int32 { rawValue }

}

extension AesKeySize: WireCodable {
    @inlinable static func decode(from reader: inout WireReader) -> AesKeySize { AesKeySize(rawValue: reader.readI32())! }
    @inlinable func encode(to writer: inout WireWriter) { writer.writeI32(rawValue) }
}

/// 导出哈希函数
public func cryptoHash(algorithm: HashAlgorithm, data: ByteArray) -> StringResult {
    let algorithmBytes = boltffiEncode { writer in writer.writeI32(algorithm.rawValue) }
    let dataBytes = boltffiEncode { writer in data.encode(to: &writer) }
    let buf = boltffi_crypto_hash(algorithmBytes, UInt(algorithmBytes.count), dataBytes, UInt(dataBytes.count))
    defer { boltffi_free_buf_u8(buf) }
    return boltffiDecodeOwnedBuf(buf.ptr, Int(buf.len)) { reader in StringResult.decode(from: &reader) }
}

/// 导出 HKDF 密钥派生
public func cryptoHkdfDerive(salt: ByteArray, ikm: ByteArray, info: ByteArray?, outputLength: UInt) -> BytesResult {
    let saltBytes = boltffiEncode { writer in salt.encode(to: &writer) }
    let ikmBytes = boltffiEncode { writer in ikm.encode(to: &writer) }
    let infoBytes = boltffiEncode { writer in writer.writeOptional(info) { writer, v in v.encode(to: &writer) } }
    let buf = boltffi_crypto_hkdf_derive(saltBytes, UInt(saltBytes.count), ikmBytes, UInt(ikmBytes.count), infoBytes, UInt(infoBytes.count), outputLength)
    defer { boltffi_free_buf_u8(buf) }
    return boltffiDecodeOwnedBuf(buf.ptr, Int(buf.len)) { reader in BytesResult.decode(from: &reader) }
}

/// 导出 PBKDF2 密钥派生
public func cryptoPbkdf2Derive(password: ByteArray, salt: ByteArray, iterations: UInt32, outputLength: UInt) -> BytesResult {
    let passwordBytes = boltffiEncode { writer in password.encode(to: &writer) }
    let saltBytes = boltffiEncode { writer in salt.encode(to: &writer) }
    let buf = boltffi_crypto_pbkdf2_derive(passwordBytes, UInt(passwordBytes.count), saltBytes, UInt(saltBytes.count), iterations, outputLength)
    defer { boltffi_free_buf_u8(buf) }
    return boltffiDecodeOwnedBuf(buf.ptr, Int(buf.len)) { reader in BytesResult.decode(from: &reader) }
}

/// 导出 AES-CBC 加密
public func cryptoAesCbcEncrypt(key: ByteArray, iv: ByteArray, plaintext: ByteArray) -> BytesResult {
    let keyBytes = boltffiEncode { writer in key.encode(to: &writer) }
    let ivBytes = boltffiEncode { writer in iv.encode(to: &writer) }
    let plaintextBytes = boltffiEncode { writer in plaintext.encode(to: &writer) }
    let buf = boltffi_crypto_aes_cbc_encrypt(keyBytes, UInt(keyBytes.count), ivBytes, UInt(ivBytes.count), plaintextBytes, UInt(plaintextBytes.count))
    defer { boltffi_free_buf_u8(buf) }
    return boltffiDecodeOwnedBuf(buf.ptr, Int(buf.len)) { reader in BytesResult.decode(from: &reader) }
}

/// 导出 AES-CBC 解密
public func cryptoAesCbcDecrypt(key: ByteArray, iv: ByteArray, ciphertext: ByteArray) -> BytesResult {
    let keyBytes = boltffiEncode { writer in key.encode(to: &writer) }
    let ivBytes = boltffiEncode { writer in iv.encode(to: &writer) }
    let ciphertextBytes = boltffiEncode { writer in ciphertext.encode(to: &writer) }
    let buf = boltffi_crypto_aes_cbc_decrypt(keyBytes, UInt(keyBytes.count), ivBytes, UInt(ivBytes.count), ciphertextBytes, UInt(ciphertextBytes.count))
    defer { boltffi_free_buf_u8(buf) }
    return boltffiDecodeOwnedBuf(buf.ptr, Int(buf.len)) { reader in BytesResult.decode(from: &reader) }
}

/// 导出 AES-CTR 加密/解密
public func cryptoAesCtr(key: ByteArray, nonce: ByteArray, data: ByteArray) -> StringResult {
    let keyBytes = boltffiEncode { writer in key.encode(to: &writer) }
    let nonceBytes = boltffiEncode { writer in nonce.encode(to: &writer) }
    let dataBytes = boltffiEncode { writer in data.encode(to: &writer) }
    let buf = boltffi_crypto_aes_ctr(keyBytes, UInt(keyBytes.count), nonceBytes, UInt(nonceBytes.count), dataBytes, UInt(dataBytes.count))
    defer { boltffi_free_buf_u8(buf) }
    return boltffiDecodeOwnedBuf(buf.ptr, Int(buf.len)) { reader in StringResult.decode(from: &reader) }
}

/// 导出生成随机 IV
public func cryptoAesGenerateIv() -> BytesResult {
    let buf = boltffi_crypto_aes_generate_iv()
    defer { boltffi_free_buf_u8(buf) }
    return boltffiDecodeOwnedBuf(buf.ptr, Int(buf.len)) { reader in BytesResult.decode(from: &reader) }
}

/// 导出 AES-GCM 加密
public func cryptoAesGcmEncrypt(key: ByteArray, nonce: ByteArray, plaintext: ByteArray, aad: ByteArray?) -> BytesResult {
    let keyBytes = boltffiEncode { writer in key.encode(to: &writer) }
    let nonceBytes = boltffiEncode { writer in nonce.encode(to: &writer) }
    let plaintextBytes = boltffiEncode { writer in plaintext.encode(to: &writer) }
    let aadBytes = boltffiEncode { writer in writer.writeOptional(aad) { writer, v in v.encode(to: &writer) } }
    let buf = boltffi_crypto_aes_gcm_encrypt(keyBytes, UInt(keyBytes.count), nonceBytes, UInt(nonceBytes.count), plaintextBytes, UInt(plaintextBytes.count), aadBytes, UInt(aadBytes.count))
    defer { boltffi_free_buf_u8(buf) }
    return boltffiDecodeOwnedBuf(buf.ptr, Int(buf.len)) { reader in BytesResult.decode(from: &reader) }
}

/// 导出 AES-GCM 解密
public func cryptoAesGcmDecrypt(key: ByteArray, nonce: ByteArray, ciphertext: ByteArray, aad: ByteArray?) -> BytesResult {
    let keyBytes = boltffiEncode { writer in key.encode(to: &writer) }
    let nonceBytes = boltffiEncode { writer in nonce.encode(to: &writer) }
    let ciphertextBytes = boltffiEncode { writer in ciphertext.encode(to: &writer) }
    let aadBytes = boltffiEncode { writer in writer.writeOptional(aad) { writer, v in v.encode(to: &writer) } }
    let buf = boltffi_crypto_aes_gcm_decrypt(keyBytes, UInt(keyBytes.count), nonceBytes, UInt(nonceBytes.count), ciphertextBytes, UInt(ciphertextBytes.count), aadBytes, UInt(aadBytes.count))
    defer { boltffi_free_buf_u8(buf) }
    return boltffiDecodeOwnedBuf(buf.ptr, Int(buf.len)) { reader in BytesResult.decode(from: &reader) }
}

/// 导出生成随机 GCM Nonce (12 字节)
public func cryptoAesGcmGenerateNonce() -> BytesResult {
    let buf = boltffi_crypto_aes_gcm_generate_nonce()
    defer { boltffi_free_buf_u8(buf) }
    return boltffiDecodeOwnedBuf(buf.ptr, Int(buf.len)) { reader in BytesResult.decode(from: &reader) }
}

/// 导出 Argon2 密码哈希
public func cryptoArgon2Hash(password: String, params: Argon2Params?) -> StringResult {
    var password = password
    let paramsBytes = boltffiEncode { writer in writer.writeOptional(params) { writer, v in v.encode(to: &writer) } }
    return password.withUTF8 { passwordBuf in
        let buf = boltffi_crypto_argon2_hash(passwordBuf.baseAddress!, UInt(passwordBuf.count), paramsBytes, UInt(paramsBytes.count))
        defer { boltffi_free_buf_u8(buf) }
        return boltffiDecodeOwnedBuf(buf.ptr, Int(buf.len)) { reader in StringResult.decode(from: &reader) }
    }
}

/// 导出 Argon2 密码哈希（使用自定义盐值）
public func cryptoArgon2HashWithSalt(password: ByteArray, salt: ByteArray, params: Argon2Params?) -> BytesResult {
    let passwordBytes = boltffiEncode { writer in password.encode(to: &writer) }
    let saltBytes = boltffiEncode { writer in salt.encode(to: &writer) }
    let paramsBytes = boltffiEncode { writer in writer.writeOptional(params) { writer, v in v.encode(to: &writer) } }
    let buf = boltffi_crypto_argon2_hash_with_salt(passwordBytes, UInt(passwordBytes.count), saltBytes, UInt(saltBytes.count), paramsBytes, UInt(paramsBytes.count))
    defer { boltffi_free_buf_u8(buf) }
    return boltffiDecodeOwnedBuf(buf.ptr, Int(buf.len)) { reader in BytesResult.decode(from: &reader) }
}

/// 导出 Argon2 密码验证
public func cryptoArgon2Verify(password: String, hash: String) -> StringResult {
    var password = password
    var hash = hash
    return password.withUTF8 { passwordBuf in
        return hash.withUTF8 { hashBuf in
            let buf = boltffi_crypto_argon2_verify(passwordBuf.baseAddress!, UInt(passwordBuf.count), hashBuf.baseAddress!, UInt(hashBuf.count))
            defer { boltffi_free_buf_u8(buf) }
            return boltffiDecodeOwnedBuf(buf.ptr, Int(buf.len)) { reader in StringResult.decode(from: &reader) }
        }
    }
}

/// 获取版本号
public func getVersion() -> String {
    let buf = boltffi_get_version()
    defer { boltffi_free_buf_u8(buf) }
    return boltffiDecodeOwnedBuf(buf.ptr, Int(buf.len)) { reader in reader.readString() }
}

@inline(__always)
private func stringFromFfi(_ ffiString: FfiString) -> String {
    guard ffiString.len > 0, let pointer = ffiString.ptr else { return "" }
    return String(decoding: UnsafeBufferPointer(start: pointer, count: Int(ffiString.len)), as: UTF8.self)
}

@inline(__always)
private func takeLastErrorMessage() -> String {
    var out = FfiString()
    ensureOk(boltffi_last_error_message(&out))
    defer { boltffi_free_string(out) }
    return stringFromFfi(out)
}

@inline(__always)
private func checkStatus(_ status: FfiStatus, context: StaticString = #function) throws {
    guard status.code == 0 else {
        throw FfiError(message: "FFI failed in \(context) with code \(status.code)")
    }
}

@inline(__always)
private func ensureOk(_ status: FfiStatus, context: StaticString = #function) {
    guard status.code == 0 else {
        fatalError("FFI failed in \(context) [\(status.code)]")
    }
}

@usableFromInline protocol WireCodable {
    static func decode(from reader: inout WireReader) -> Self
    func encode(to writer: inout WireWriter)
}

@usableFromInline struct WireReader {
    @usableFromInline let data: Data
    @usableFromInline var position: Int
    @inlinable init(ptr: UnsafePointer<UInt8>, len: Int) { self.data = Data(bytes: ptr, count: len); self.position = 0 }

    @inlinable mutating func readU8() -> UInt8 { let v = data[position]; position += 1; return v }
    @inlinable mutating func readI8() -> Int8 { Int8(bitPattern: readU8()) }
    @inlinable mutating func readU16() -> UInt16 { let v = data.withUnsafeBytes { $0.loadUnaligned(fromByteOffset: position, as: UInt16.self) }; position += 2; return v }
    @inlinable mutating func readI16() -> Int16 { Int16(bitPattern: readU16()) }
    @inlinable mutating func readU32() -> UInt32 { let v = data.withUnsafeBytes { $0.loadUnaligned(fromByteOffset: position, as: UInt32.self) }; position += 4; return v }
    @inlinable mutating func readI32() -> Int32 { Int32(bitPattern: readU32()) }
    @inlinable mutating func readU64() -> UInt64 { let v = data.withUnsafeBytes { $0.loadUnaligned(fromByteOffset: position, as: UInt64.self) }; position += 8; return v }
    @inlinable mutating func readI64() -> Int64 { Int64(bitPattern: readU64()) }
    @inlinable mutating func readF32() -> Float { Float(bitPattern: readU32()) }
    @inlinable mutating func readF64() -> Double { Double(bitPattern: readU64()) }
    @inlinable mutating func readBool() -> Bool { readU8() != 0 }

    @inlinable mutating func readString() -> String {
        let len = Int(readU32())
        guard len > 0 else { return "" }
        let start = position
        position += len
        return String(decoding: data[start..<(start + len)], as: UTF8.self)
    }

    @inlinable mutating func readBytes() -> Data {
        let len = Int(readU32())
        guard len > 0 else { return Data() }
        let start = position
        position += len
        return data[start..<(start + len)]
    }

    @inlinable mutating func readDuration() -> TimeInterval {
        let seconds = readU64()
        let nanoseconds = readU32()
        return Double(seconds) + (Double(nanoseconds) / 1.0e9)
    }

    @inlinable mutating func readTimestamp() -> Date {
        let seconds = readI64()
        let nanoseconds = readU32()
        let delta = seconds >= 0
            ? (Double(seconds) + (Double(nanoseconds) / 1.0e9))
            : (Double(seconds) - (Double(nanoseconds) / 1.0e9))
        return Date(timeIntervalSince1970: delta)
    }

    @inlinable mutating func readUuid() -> UUID {
        let hi = readU64()
        let lo = readU64()
        var uuid: uuid_t = (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
        var hiBe = hi.bigEndian
        var loBe = lo.bigEndian
        withUnsafeMutableBytes(of: &uuid) { uuidBytes in
            Swift.withUnsafeBytes(of: &hiBe) { uuidBytes[0..<8].copyBytes(from: $0) }
            Swift.withUnsafeBytes(of: &loBe) { uuidBytes[8..<16].copyBytes(from: $0) }
        }
        return UUID(uuid: uuid)
    }

    @inlinable mutating func readUrl() -> URL {
        guard let url = URL(string: readString()) else { fatalError("Invalid URL") }
        return url
    }

    @inlinable mutating func readOptional<T>(_ body: (inout WireReader) -> T) -> T? {
        guard readU8() != 0 else { return nil }
        return body(&self)
    }

    @inlinable mutating func readArray<T>(_ body: (inout WireReader) -> T) -> [T] {
        let count = Int(readU32())
        guard count > 0 else { return [] }
        var result = [T]()
        result.reserveCapacity(count)
        for _ in 0..<count { result.append(body(&self)) }
        return result
    }

    @inlinable mutating func readBlittable<T>() -> T {
        let v = data.withUnsafeBytes { $0.loadUnaligned(fromByteOffset: position, as: T.self) }
        position += MemoryLayout<T>.stride
        return v
    }

    @inlinable mutating func readBlittableArray<T>() -> [T] {
        let count = Int(readU32())
        guard count > 0 else { return [] }
        let byteCount = count * MemoryLayout<T>.stride
        let start = position
        position += byteCount
        return data.withUnsafeBytes { rawBuffer in
            Array<T>(unsafeUninitializedCapacity: count) { buffer, initialized in
                memcpy(buffer.baseAddress!, rawBuffer.baseAddress!.advanced(by: start), byteCount)
                initialized = count
            }
        }
    }

    @inlinable mutating func read<T: WireCodable>() -> T {
        T.decode(from: &self)
    }
}

@usableFromInline struct WireWriter {
    @usableFromInline var bytes: [UInt8]
    @inlinable init() { self.bytes = [] }

    @inlinable mutating func writeU8(_ v: UInt8) { bytes.append(v) }
    @inlinable mutating func writeI8(_ v: Int8) { writeU8(UInt8(bitPattern: v)) }
    @inlinable mutating func writeU16(_ v: UInt16) { var val = v; Swift.withUnsafeBytes(of: &val) { bytes.append(contentsOf: $0) } }
    @inlinable mutating func writeI16(_ v: Int16) { writeU16(UInt16(bitPattern: v)) }
    @inlinable mutating func writeU32(_ v: UInt32) { var val = v; Swift.withUnsafeBytes(of: &val) { bytes.append(contentsOf: $0) } }
    @inlinable mutating func writeI32(_ v: Int32) { writeU32(UInt32(bitPattern: v)) }
    @inlinable mutating func writeU64(_ v: UInt64) { var val = v; Swift.withUnsafeBytes(of: &val) { bytes.append(contentsOf: $0) } }
    @inlinable mutating func writeI64(_ v: Int64) { writeU64(UInt64(bitPattern: v)) }
    @inlinable mutating func writeF32(_ v: Float) { writeU32(v.bitPattern) }
    @inlinable mutating func writeF64(_ v: Double) { writeU64(v.bitPattern) }
    @inlinable mutating func writeBool(_ v: Bool) { writeU8(v ? 1 : 0) }

    @inlinable mutating func writeString(_ v: String) {
        var s = v
        s.withUTF8 { utf8 in
            writeU32(UInt32(utf8.count))
            bytes.append(contentsOf: utf8)
        }
    }

    @inlinable mutating func writeBytes(_ v: Data) {
        writeU32(UInt32(v.count))
        bytes.append(contentsOf: v)
    }

    @inlinable mutating func writeDuration(_ v: TimeInterval) {
        if v.rounded(.down) > Double(Int64.max) { fatalError("Duration overflow") }
        if v < 0 { fatalError("Invalid duration") }
        let seconds = UInt64(v)
        let nanoseconds = UInt32((v - Double(seconds)) * 1.0e9)
        writeU64(seconds)
        writeU32(nanoseconds)
    }

    @inlinable mutating func writeTimestamp(_ v: Date) {
        var delta = v.timeIntervalSince1970
        var sign: Int64 = 1
        if delta < 0 { sign = -1; delta = -delta }
        if delta.rounded(.down) > Double(Int64.max) { fatalError("Timestamp overflow") }
        let seconds = Int64(delta)
        let nanoseconds = UInt32((delta - Double(seconds)) * 1.0e9)
        writeI64(sign * seconds)
        writeU32(nanoseconds)
    }

    @inlinable mutating func writeUuid(_ v: UUID) {
        var uuid = v.uuid
        let (hi, lo) = Swift.withUnsafeBytes(of: &uuid) { raw -> (UInt64, UInt64) in
            let hiBe = raw.loadUnaligned(fromByteOffset: 0, as: UInt64.self)
            let loBe = raw.loadUnaligned(fromByteOffset: 8, as: UInt64.self)
            return (UInt64(bigEndian: hiBe), UInt64(bigEndian: loBe))
        }
        writeU64(hi)
        writeU64(lo)
    }

    @inlinable mutating func writeUrl(_ v: URL) { writeString(v.absoluteString) }

    @inlinable mutating func writeOptional<T>(_ v: T?, _ body: (inout WireWriter, T) -> Void) {
        guard let value = v else { writeU8(0); return }
        writeU8(1)
        body(&self, value)
    }

    @inlinable mutating func writeArray<T>(_ v: [T], _ body: (inout WireWriter, T) -> Void) {
        writeU32(UInt32(v.count))
        for item in v { body(&self, item) }
    }

    @inlinable mutating func writeBlittable<T>(_ value: T) {
        var copy = value
        Swift.withUnsafeBytes(of: &copy) { bytes.append(contentsOf: $0) }
    }

    @inlinable mutating func writeBlittableArray<T>(_ v: [T]) {
        writeU32(UInt32(v.count))
        v.withUnsafeBytes { bytes.append(contentsOf: $0) }
    }

    @inlinable mutating func write<T: WireCodable>(_ v: T) { v.encode(to: &self) }

    @inlinable func finalize() -> [UInt8] { bytes }
}

@inlinable func boltffiInvokeWireCallback(
    _ callback: (@convention(c) (UInt64, UnsafePointer<UInt8>?, UInt, FfiStatus) -> Void)?,
    _ callbackData: UInt64,
    _ encoded: [UInt8],
    _ status: FfiStatus
) {
    encoded.withUnsafeBufferPointer { buf in
        callback?(callbackData, buf.baseAddress, UInt(buf.count), status)
    }
}

@inlinable func boltffiDecodeOwnedBuf<T>(_ ptr: UnsafePointer<UInt8>?, _ len: Int, _ decode: (inout WireReader) -> T) -> T {
    var reader = WireReader(ptr: ptr!, len: len)
    return decode(&reader)
}

@inlinable func boltffiDecodeOwnedBuf<T>(_ ptr: UnsafePointer<UInt8>?, _ len: Int, _ decode: (inout WireReader) throws -> T) throws -> T {
    var reader = WireReader(ptr: ptr!, len: len)
    return try decode(&reader)
}

@inlinable func boltffiEncode(_ body: (inout WireWriter) -> Void) -> [UInt8] {
    var writer = WireWriter()
    body(&writer)
    return writer.finalize()
}
